app/controllers/places_controller.rb
app/views/places/index.html.slim
config/routes.rb

Closes #11 
- トップページとPlacesControllerの作成。
- ルーティングの変更
`/` にアクセスして `PlacesController#index` が表示されればokです！

Add: places_controller & topページ

---

app/views/layouts/application.html.slim
app/views/shared/_header.html.slim

Closes #23
行ったバグ修正や機能追加の概要を説明しましょう。外部のタスク管理ツールを利用している場合、そのツールが発行するタスクへのリンクを貼ってもいいでしょう。
UI に対する変更を行った場合、変更前 / 後 の画像があると理解の助けになります。
行った修正をレビュアーが確認するための手順を記載しましょう。例えば以下のように。
1. Gem を追加したので `bundle install` を実行してください
2. カラムを追加したので `bundle exec rails db:migrate` を実行してください
3. 顧客一覧画面に「資本金」項目が追加され、デフォルトが「未入力」になっていることを確認してください
行った修正が影響するであろう範囲を記載しましょう。レビュアーが修正の影響範囲を予測する助けになります。
修正内容で気になる部分があればここに書き留めておきましょう。
例えば「ここのコードはもっとイケてる書き方がある気がしています」、例えば「この部分は `FIXME` を残していますが時間の都合によりご勘弁を」など。
レビュアーとのコミュニケーションの助けになります。
[![Image from Gyazo](https://i.gyazo.com/9099f3cb5e467cdd504d3f1fd0dbe2eb.png)](https://gyazo.com/9099f3cb5e467cdd504d3f1fd0dbe2eb)

Add: header

---

app/views/shared/_header.html.slim

[![Image from Gyazo](https://i.gyazo.com/dfca65f7c625aa093cd58665e5420768.png)](https://gyazo.com/dfca65f7c625aa093cd58665e5420768)
行ったバグ修正や機能追加の概要を説明しましょう。外部のタスク管理ツールを利用している場合、そのツールが発行するタスクへのリンクを貼ってもいいでしょう。
UI に対する変更を行った場合、変更前 / 後 の画像があると理解の助けになります。
行った修正をレビュアーが確認するための手順を記載しましょう。例えば以下のように。
1. Gem を追加したので `bundle install` を実行してください
2. カラムを追加したので `bundle exec rails db:migrate` を実行してください
3. 顧客一覧画面に「資本金」項目が追加され、デフォルトが「未入力」になっていることを確認してください
行った修正が影響するであろう範囲を記載しましょう。レビュアーが修正の影響範囲を予測する助けになります。
修正内容で気になる部分があればここに書き留めておきましょう。
例えば「ここのコードはもっとイケてる書き方がある気がしています」、例えば「この部分は `FIXME` を残していますが時間の都合によりご勘弁を」など。
レビュアーとのコミュニケーションの助けになります。

Fix: header

---

Gemfile
Gemfile.lock

とりあえずHerokuにデプロイしました。
11月後半に有料になっちゃうんで、その時また移行しましょう笑
詳細はissueにまとめてます => Closes #47 
デプロイしたURLはこちら
https://pluspo.herokuapp.com

Herokuにデプロイした

---

README.md

close #56
以前のテーブル設計から変更があったのでER図を変更しました
[![Image from Gyazo](https://i.gyazo.com/eddc1242249969aaee870c8a820a2cbb.jpg)](https://gyazo.com/eddc1242249969aaee870c8a820a2cbb)
PluspoのリポジトリのREADME.mdから確認してください

Change: ER図の変更

---

Gemfile
Gemfile.lock
app/models/user.rb
config/initializers/sorcery.rb
db/migrate/20220929041910_sorcery_core.rb
db/schema.rb

Closes #10
Sorceryインストール、Userモデルを作成しました。 
1. Gem を追加したので `bundle install` を実行してください
2. カラムを追加したので `bundle exec rails db:migrate` を実行してください
管理画面作ることを考えてUserモデルにroleカラム追加しました！
Userのログイン機能の実装もやってしまったほうがいいですか？（緊急ではなさそう）

Add: sorceryでユーザーモデル追加

---

app/controllers/application_controller.rb

close #73 
ソートの順番を以下のようにしました
1.日付(date_and_day_of_week)
2.時間(full_time)
3.スポーツ名
[![Image from Gyazo](https://i.gyazo.com/19532394b9cd950e83793efdc2a7ce5c.png)](https://gyazo.com/19532394b9cd950e83793efdc2a7ce5c)
[![Image from Gyazo](https://i.gyazo.com/f68cdda7cadf3831b00b9329ff0995d9.png)](https://gyazo.com/f68cdda7cadf3831b00b9329ff0995d9)
`rails s`で起動して確認してみてください
application_controller
view
変なとこあったら報告ください

Add: 検索した施設リストのソート変更

---

app/assets/stylesheets/application.css
app/views/places/_place_table.html.slim

Close #84 
ページネーションの色を変えました。
ページネーションの位置も真ん中に変更しています。
Searchボタンはいじってません。
一部のCSSを強制してます。何か不具合あったら教えてください

Add: kaminariの色を変えました

---

app/views/schedules/_schedule.html.slim

Closes #93
スポーツ施設の名前をクリックしたら右側遷移します
終わったら消す

Add: Turboをオフにする

---

app/views/shared/_search_schedule_form.html.slim

Close #99 
右上Searchボタンの色変わってるので確認してみてください

Fix: searchボタンの色修正

---

Dockerfile
entrypoint.sh

Magiaデプロイ用

---

config/database.yml

Add: デプロイMagia /change database.yml

---

app/assets/config/manifest.js
app/javascript/application.js
app/javascript/controllers/index.js
package.json
yarn.lock

Fix: Magiaデプロイのため諸々修正

---

Dockerfile

close #130 
Magiaデプロイ用の変更。nodejs関連の記述をコメントアウト。
1. magiaでデプロイできれば良し

Magiaデプロイ変更(Bootstrap)

---

app/views/places/_place.html.slim

close #54
_place.html.alimのaタグをlink_toに変更
[![Image from Gyazo](https://i.gyazo.com/7851b82c67cdee6683be435e8fd09281.png)](https://gyazo.com/7851b82c67cdee6683be435e8fd09281)
1. TOPページにアクセス
2. 施設詳細画面の各リンクが表示されることを確認

Improve: _place.html -aタグをlink_toに変更

---

db/fixtures/01_place.rb

* seed_fuを2回打ってもエラーが出ないようにseed_fu実行時のidの渡し方などを変更
close #132 
1. seed_fuを2回実行

seed_fuを2回打ってもエラーが出ないように

---

app/views/shared/_header.html.slim

close #163 
検索ボタンが返ってきました！
[![Image from Gyazo](https://i.gyazo.com/1524d680fbd049e0b673293e1b8a3972.png)](https://gyazo.com/1524d680fbd049e0b673293e1b8a3972)

ヘッダーから検索ボタンが消えるバグを修正

---

Gemfile
app/helpers/application_helper.rb
app/models/schedule.rb
config/initializers/ransack.rb
db/fixtures/01_place.rb
db/fixtures/02_schedule.rb

close #174 
db:seed_fuを打つ度にスケジュールが複製されていたバグを修正しました。
あとついでにrubocopの修正も行いました。

db:seed_fuで同じスケジュールが作成されないように修正

---

app/views/schedules/_schedule.html.slim

close #178 
施設詳細リンクをRESTfulなものに修正しました。
本番環境でOKならマージします

Fix: 施設詳細リンクをRESTfulなものに修正

---

config/environments/development.rb

close #183 
今更ながら、ngrokを導入。
localhostを別端末でも開けるので、デザイン確認に便利！！！
検証ツールより確実なので、レイアウトを調整した場合はngrokで確認してからPR作成お願いします
1. [公式HP](https://ngrok.com/download)を参考にngrokをPCにインストール（ユーザー登録も必要です！）
2. ``bin/rails s``と``ngrok http http://localhost:3000``で起動します。
3. 下記画像のForwardingの後ろのURLにアクセス
[![Image from Gyazo](https://i.gyazo.com/4fc634fe3a981631b2d782203fa4a660.png)](https://gyazo.com/4fc634fe3a981631b2d782203fa4a660)
4. QRコードを作成
[![Image from Gyazo](https://i.gyazo.com/beefa4528494e66d8ed724a910bca430.png)](https://gyazo.com/beefa4528494e66d8ed724a910bca430)
5. 作成したQRコードをスマホで読み込むとPC以外でもlocalhostを開けます！！
特になし

Add: ngrok使うためにhostを許可

---

app/views/shared/_footer.html.slim

- Google Formで問い合わせフォーム作成
- フッターに問い合わせフォームのリンクを追加
close #157
1. TOPページにアクセス
2. フッターに「お問い合わせ」が表示されることを確認
3. 「お問い合わせ」ボタンをクリック
4. 作成したGoogle Formに遷移することを確認
なし

Google Formで問い合わせフォーム作成
